### ISSUE TITLE
Filthy Weeaboo

### ISSUE THREAD

**Issue by goffrier** [DNA8777/Saitama-v2#1]
Saitama sucks you filthy weeb

**Comment by goffrier** [comment]
garoh ftw

**Comment by goffrier** [comment]
![image](https://user-images.githubusercontent.com/40528055/60447318-7dcebd00-9c23-11e9-8671-530db7fed067.png)

**Comment by DNA8777** [comment]
this is why i don’t show mt repos on reiswitched very often. you jew
